			/*******************************************
			********************************************
			*****GENERATED BY LGE DCV HN GMOCK 2.0******
			********************************************
			*******************************************/
#include <gmock/gmock.h>
class MockPowerManager : public PowerManager{
public:
    MOCK_METHOD(int, getPowerMode, (), (override));
    MOCK_METHOD(int, getPowerState, (), (override));
};
